SectionVerb {
	EnableSequence [
		cset "name='QUAT_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia3 Mixer SLIMBUS_0_TX' 1"

		cset "name='AIF1_CAP Mixer SLIM TX6' 1"
		cset "name='CDC_IF TX6 MUX' DEC6"
	]

	DisableSequence [
		cset "name='QUAT_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia3 Mixer SLIMBUS_0_TX' 0"

		cset "name='AIF1_CAP Mixer SLIM TX6' 0"
		cset "name='CDC_IF TX6 MUX' ZERO"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker Output"

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackPriority 100
	}
}

SectionDevice."Earpiece" {
	Comment "Earpiece Output"

	Value {
		PlaybackPCM "hw:${CardId},0"
		PlaybackPriority 10
	}
}

SectionDevice."Mic" {
	Comment "Phone Bottom Mic"

	EnableSequence [
		cset "name='ADC MUX6' AMIC"
		cset "name='AMIC MUX6' ADC1"
	]

	DisableSequence [
		cset "name='AMIC MUX6' ZERO"
		cset "name='ADC MUX6' ZERO"
	]

	Value {
		CapturePCM "hw:${CardId},2"
		CaptureMixerElem "ADC1"
		CapturePriority 100
	}
}
