Syntax 4

SectionUseCase."HiFi" {
	File "/Xiaomi/dipper/HiFi.conf"
	Comment "HiFi quality music."
}

SectionUseCase."Voice Call" {
	File "/Xiaomi/dipper/VoiceCall.conf"
	Comment "Voice call."
}

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"

BootSequence [
	cset "name='RX1 Digital Volume' 80"
	cset "name='RX2 Digital Volume' 80"
	cset "name='ADC1 Volume' 5"
	cset "name='ADC3 Volume' 16"
	cset "name='DEC6 Volume' 80"
	cset "name='DEC7 Volume' 96"
]
